id: PE6A4A742
initial_creation_type: input
source_metadata:
  title: Jamyang Khyentse Wangpo Series
  language: pt
  description: 'Texts by and about the great Rimé (“nonsectarian”) master Jamyang
    Khyentse Wangpo (''jam dbyangs mkhyen brtse''i dbang po, 1820–1892), one of the
    most influential figures of recent times:'
  volume:
    a01f9adb6d834ad5818c8ad27bcf94df:
      title: 'A Few Words of Commentary to Clarify The Essence of Nectar: Graduated
        Stages of the Path—Advice for Renunciant Meditators'
      parent: Advice
    748c807278b04b73b037295ab01c7c23:
      title: 'The Essence of Nectar: Graduated Stages of the Path — Advice for Renunciant
        Meditators'
      parent: Advice
    5dc1a2c190724f14a68f32b6f106be31:
      title: Biography of Jamyang Khyentse Wangpo
      parent: Biography
    6d7595dd96b943fab6c1bd8c779ef7cb:
      title: The Life of Jamyang Khyentse Wangpo
      parent: Biography
    ca492973befa4878b04169004fdc257a:
      title: 'The Seed of Reasoning: Notes on the Five Great Logical Arguments of
        the Middle Way'
      parent: Buddhist Philosophy
    cc81c8dd2ce4452f8b7b855e25cd66bb:
      title: 'A Few Remarks: An Explanation of the Praise to Noble Mañjuśrī known
        as Glorious Wisdom’s Excellent Qualities'
      parent: Commentaries
    b91586018e9447479ce729c1ef3297c5:
      title: Guide to the Practice of Narak Kong Shak
      parent: Confession
    179ee75942d54a82a2bc19d35d90febc:
      title: 'The Rain of Virtue and Goodness: A Short Practice for Consecrating Representations
        of Enlightened Body, Speech and Mind'
      parent: Consecration
    a60d95c3a0b5477b8c28ff9f530502b0:
      title: 'The Vajra Lute: A Brief Fulfilment for the Guru Practice of Vidyādhara-Assembly'
      parent: Fulfilment
    125b94f4795140f793f5101650ab5d2f:
      title: 'A Shortcut to the Siddhi of Immortality: Guru Yoga of Union with the
        Three Deities of Long Life'
      parent: Guru Yoga
    ac4166365d99492dbd93d846583e45fa:
      title: A Brief History of the Sacred Image of White Tārā
      parent: History
    c8788bec433c405fb6101b021bb728d6:
      title: The History of the Hearing Lineage of the Profound and Secret Practice
        of Siṃhamukhā
      parent: History
    c00a4573321b447fa8ace85773ab3b06:
      title: 'A Shower of Great Bliss: A Lineage Prayer for the Guru Yoga based on
        Vajrasattva'
      parent: Lineage Prayers
    b8294cf7d0044cadaad94b60950f68b7:
      title: 'Bestower of the Light of Intelligence: A Prayer to the Lineage of the
        Profound Sādhana Based Upon the Praise to Venerable Mañjughoṣa'
      parent: Lineage Prayers
    83758d8fcf9d4cef8b9d8aa168111225:
      title: 'Source of Magnificent Blessing: A Prayer to the Lineage of the Secret
        Practice of the Great Compassionate One, Natural Liberation of Suffering'
      parent: Lineage Prayers
    486cf6c595ad4a4497a24e5d798c4e08:
      title: Supplement to the Omniscient Ngorchen Kunga Zangpo’s Prayer to the Lineage
        of Parting from the Four Attachments
      parent: Lineage Prayers
    37f9fbb9808041829aa06157fe921d94:
      title: 'The Flower of Faith: A Prayer to the Twenty-Five Founders of Buddha''s
        Teachings in Tibet'
      parent: Lineage Prayers
    b463948786df4a0392a55e03115aac12:
      title: 'The Garland of Utpala Flowers: A Prayer to the Masters of the Lineage
        of Zabtik Drolchok'
      parent: Lineage Prayers
    329505fe98a04e7199abc4bb18e89e5e:
      title: 'The Seed of Faith: A Prayer to the Sublime Ones'
      parent: Lineage Prayers
    8c48840afcb64f1b92fb5b9f2f8c76ad:
      title: 'The Shower of Great Bliss: A Prayer to the Lineage of the Female Awareness-Holder
        (Yumka)'
      parent: Lineage Prayers
    575b85bdc570464e97cbe1c7be886c45:
      title: Ambrosia for the Mind
      parent: Lojong
    6d9f0f3b57fb473c8afecdb8250fb299:
      title: 'Nectar of the Heart: An Experiential Song of Parting from the Four Attachments'
      parent: Lojong
    6759b5cd9e6e405398c66e2321a07a0c:
      title: 'Words of Advice on Accomplishing Immortality: An Extremely Concise Daily
        Practice Uniting the Short Lineages of Amitāyus and Hayagrīva'
      parent: Longevity
    27e19e84c51240ba8d81adecaf0b0eaa:
      title: 'Wisdom''s Bestowal: A Way to Accumulate the Recitation of the Tantra
        ''Chanting the Names of Mañjuśrī'' (Mañjuśrī Nāma Saṃgīti)'
      parent: Mañjuśrī
    5b5c7ea0f1384f809b44a5c2434ccc1c:
      title: 'A Profound Concentration of Nectar: Essentialized Stages of Visualization
        for the Preliminary Practices of the Heart Essence of the Vast Expanse (Longchen
        Nyingtik)'
      parent: Ngöndro
    4dcfeba77eb24072822f4ba4c05d2a9f:
      title: 'Illuminating the Excellent Path to Omniscience: Notes on the Longchen
        Nyingtik Ngöndro'
      parent: Ngöndro
    437cc2cc3c164316a72bf8d8c6bb9acc:
      title: 'The Excellent Path to Enlightenment: A Brief Practice of the Preliminaries'
      parent: Ngöndro
    71d7498d2d8a4493aac3d085bcd50c23:
      title: A Brief Practice of Consecrating Amṛta for the Vidyādhara Assembly
      parent: Offering
    94109793868d4965bf5ca3920803b869:
      title: Concise Seven-Heap Maṇḍala Offering
      parent: Offering
    2c6887cf2cd14068a12a35e31c6e671d:
      title: Offering the Eight Auspicious Substances and Seven Emblems of Royalty
      parent: Offering
    12f7d66811a9422d8f72e16a157452b7:
      title: Short Maṇḍala Offering
      parent: Offering
    ddbc7cb462ad4e2ba54b4c5bad3a26ad:
      title: 'The Offering Clouds of the Indestructible Ladies of Sound: Concise Garland
        of Offerings of the Sixteen Vajra Goddesses'
      parent: Offering
    cb85636e17df41e38a6c5a457f60dd6a:
      title: In Praise of Jamyang Khyentse Wangpo
      parent: Praise
    ccbf013a09df4415b278321074f2d71b:
      title: 'Music to Delight the Ḍākinī: A Praise to the Deathless Mandāravā'
      parent: Praise
    26eb681e67f14c54b1f527b3ff3f525c:
      title: A Short Prayer Based on the Life and Liberation of the All-Knowing, All-Seeing
        Jamyang Khyentse Wangpo
      parent: Prayers
    e1e719921e5b4a2a9bdd2b6b43755b15:
      title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
      parent: Prayers
    c9fecbbd9d21453f8f4ce9f31164ad1e:
      title: Prayer to Jamyang Khyentse Wangpo
      parent: Prayers
    96ebe69efaf342de8cbec296b43258ba:
      title: Prayer to Jamyang Khyentse Wangpo and Jamyang Khyentse Chökyi Lodrö
      parent: Prayers
    430f55130440490f9a5804f766a90702:
      title: Prayer to Jamyang Khyentse Wangpo, Jamgön Kongtrul and Jamyang Khyentse
        Chökyi Lodrö
      parent: Prayers
    baad97a2e4ae48b2a2ebf322b5c4d079:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    b3e6455a321942529fa162eecd779d0e:
      title: Prayer to Root and Lineage Masters, and the Assembly of Deity, Ḍākinīs
        and Dharma Protectors of the Sakya Lineage
      parent: Prayers
    a2ec9895363540998a69bcb3db83a148:
      title: Prayer to Thangtong Gyalpo
      parent: Prayers
    3d11e847e82f4cbb8d4880fbc45ef600:
      title: Prayer to the Siddha Virūpa
      parent: Prayers
    853f74cee06f428aa62f89f9310ef4fe:
      title: Supplication to Lord Buddha together with the Sixteen Arhats
      parent: Prayers
    51d79562aafa4d999890149c9dcddc90:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Prayers
    d659d4eeeb6f4e77892d235e3ef2243d:
      title: 'The Melody of Complete Accomplishment: A Prayer to Those Praised as
        Ornaments of the Practice Lineage'
      parent: Prayers
    7fb8d2f40d0b4decb67260968ccd9839:
      title: 'The Sweet-Sounding Song that Fulfils All Aims: A Prayer to Noble Tārā
        Combined with Her Root Mantra'
      parent: Prayers
    f047c5cc41934912ba0090290a4105e3:
      title: Words of Jamyang Khyentse
      parent: Prayers
    d82e780db0544bc7abc2edf69f88f392:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Prayers to Guru Rinpoche
    adeffd7489204df68e61008dfdec020a:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Prayers to Guru Rinpoche
    7b0ea21ed1ca46f79444aacbf8651c23:
      title: 'The Chariot of the Vidyādharas: An Aspiration Prayer for Travelling
        to the Realm of Lotus Light'
      parent: Prayers to Guru Rinpoche
    fddb24caef92454d8beeeb9287c1f3bb:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Prayers to Guru Rinpoche
    761d96f6c91a4b24ac7795d19d883eb7:
      title: 'The Heart of Blessings: A Brief Anthology of Prayers to Guru Rinpoche
        and the Twenty-Five Disciples, the King and Subjects'
      parent: Prayers to Guru Rinpoche
    94e97e9a7dbe4ac29aa246f75f860a81:
      title: 'Turning Back Obstacles and Adverse Circumstances: A Prayer to Orgyen
        Rinpoche, Embodiment of All Sources of Refuge'
      parent: Prayers to Guru Rinpoche
    377f1dad3e4940f48922ebb207839d70:
      title: 'Wish-Fulfilling Feast of Siddhis: An Aspiration Prayer to Orgyen Rinpoche,
        the Precious Master of Oddiyana'
      parent: Prayers to Guru Rinpoche
    757fa7f66a89401ca38b7c102e147f78:
      title: A Brief Practice of Paying Homage and Making Offerings to the Sixteen
        Elders
      parent: Sādhanas
    2c8b20ad7681431f955922f0ee8cb218:
      title: Activities for Uncovering Primordial Wisdom from the Chimé Pakmé Nyingtik,
        ‘The Heart Essence of the Sublime Lady of Immortality’
      parent: Sādhanas
    6c0ea7a60eda4ae59f6b9e1a4dd59c7f:
      title: 'Fast Track to Happiness and Peace: A Very Brief Meditation and Recitation
        of the Medicine Buddha'
      parent: Sādhanas
    ccfed4c2532e4d9699df77455362ad69:
      title: 'Moonlight of Pacifying Amṛta: A Daily Visualization and Recitation for
        the Dispeller of All Samaya Corruptions and Pollutions'
      parent: Sādhanas
    a01de9d8e74248fda3b56f6e28580d48:
      title: The Essential Activity Manual for the Awesome Ones’ Assembly, the Heart
        Practice of Vidyādharas, from the Heart Essence of the Vast Expanse
      parent: Sādhanas
    d7004874e96b485e9316fb4a01434558:
      title: 'The Heart of Wish-Fulfilling Jewels: A Brief Practice for Paying Homage
        and Making Offerings to the Buddha together with his retinue of Arhats'
      parent: Sādhanas
    a3e0cba44d0948088128ced1e3243f48:
      title: 'The Single Mudrā: A Daily Practice for the Awesome Ones’ Assembly (Palchen
        Düpa), the Heart Practice of the Awareness-Holders'
      parent: Sādhanas
    cdc448215c47480eb221944ed4cf0266:
      title: The Single-Form Daily Practice from Chimé Pakmé Nyingtik (The Heart Essence
        of the Sublime Lady of Immortality)
      parent: Sādhanas
    fb2c8670cc0f48c48165888781f23572:
      title: The Visualization of the Four Goddesses of the Great Compassionate One,
        Natural Liberation of Suffering
      parent: Sādhanas
    93b52b60ea494797b1aea191b388ad81:
      title: 'Increasing Life and Vitality: A Practice for Freeing Lives'
      parent: Saving Lives
    87eab1b181b943318eb7be85b8d3a7b5:
      title: A Section of the Vajrakīla Root Tantra
      parent: Tantra
    b5ca0ba2afa3446fa5a7bf39d8bc116c:
      title: The Twenty-Eight Commitments
      parent: Tantra
    761853466b2542e990b786b961a447f8:
      title: 'A Glorious Garland of the Two Accomplishments: An Abridged Feast-Offering
        for the Female Practice of the Ḍākinī'
      parent: Tsok
    c742c0b810b54840ac3812416c081e5a:
      title: 'Essence of Accomplishment: A Concise Feast-Offering to Noble Tārā'
      parent: Tsok
    434cacc7c0ce4e66a0924ffe5125d751:
      title: 'Harmonious Clouds of Sublime and Lasting Bliss: A Vajra Song for the
        Tsok Feast Offering to Venerable and Exalted Vajrayoginī'
      parent: Tsok
    1e8983cd2400458393bd166860d37e67:
      title: Short Tsok Offering to the Powerful Lady Kurukullā
      parent: Tsok
    3dfca88eb52d4351942684fa5188f713:
      title: 'Song and Dance to Delight the Ḍākas and Ḍākinīs: An Aspiration for the
        Sixfold Satisfaction of the Maṇḍala of the Feast-Gathering'
      parent: Tsok
created_at: '2022-02-28T23:57:51.905105'
last_modified_at: '2022-02-28T23:57:51.905108'
